### ISSUE TITLE
Add read_model suffix to read model tables

### ISSUE THREAD

**Issue by fabriziosestito** [trento-project/web#201]
..for the sake of clarity

**Comment by rtorrero** [comment]
I started playing a bit with this idea and it turned into a bit of a mess when we reach associations:

When updating e.g. `sap_system_read_model.ex`, if we don't alter the 

```
has_many :application_instances, ApplicationInstanceReadModel,
```
line, the tests complain:
```
** (ArgumentError) schema Trento.SapSystemReadModel does not have association :application_instances_read_model
```

If we have to change the `has_many` and also add the suffix there, we lose a bit of readability. After a quick chat with @fabriziosestito we agreed to close this one as WONTFIX for now
