### ISSUE TITLE
EULA is only showed after a page refresh

### ISSUE THREAD

**Issue by arbulu89** [trento-project/web#397]
The EULA acceptance view is only showed when the whole page is refreshed. This might create some issues, as we don't really send any notification to the user.

As an improvement, we should prompt the EULA view or some user notification once the premium setup is activated after a new discovery with a sles4sap subscription is received.

![eula](https://user-images.githubusercontent.com/36370954/164464879-a2807929-5361-43be-887d-e984fb00b660.gif)

**Comment by fabriziosestito** [comment]
Closed by #398
